version: "1"

services: 

  ytube:

    build: .

    image: juanabascal/ytube:latest

    volumes:

    # volume created in /var/lib/docker/volumes/ytube-download_music/_data/

      - music:/usr/src/app/outputs

volumes:

  music: